export const QUERY_KEY = {
    CART: 'CART',
    VARIANT: 'variant',
    PRODUCTS: 'products',
    HOT_PRODUCTS: 'HOT_PRODUCT',
    DISCOUNT_PRODUCTS: 'DISCOUNT_PRODUCT',
    FILTER_BYCATE: 'products-cate',
    PRODUCTS_LAZY: 'products_lazy',
    CATEGORIES: 'categories',
    SIZES: 'sizes',
    COLORS: 'colors',
    TAGS: 'tags',
    MENU: 'categories-menu',
    LATEST: 'latest',
    DEALS: 'deals',
    REPORT_REVIEWS: 'report-review',
    RELATED: 'related',
    POPULARCATEGORIES: 'poularCategories',
    USERS: 'users',
    USERS_PROFILE: 'profile',
    VNPAY_RETURN: 'vnpay-return',
    ORDERS: 'orders',
    MY_ORDERS: 'my-orders',
    CHECKOUT: 'checkout',

    SHIPPING_SERVICES: 'shippingServices',
    GET_PROVINCE: 'province',
    GET_DISTRICT: 'district',
    GET_WARD: 'ward',
    CALCULATE_FEE: 'calculateFee',

    // Stats
    TOTAL_STATS: 'totalStats',
    DAILY_STATS: 'dailyStats',
    MONTHLY_STATS: 'monthlyStats',
    YEARLY_STATS: 'yearlyStats',
    DATE_RANGE: 'dateRange',
    LOCATION: 'location',
    PRODUCT_STATS: 'productStats',
    TOP_BUYERS: 'topBuyers',
    // wishlist
    WISHLIST: {
        LIST: 'wishlist',
        ADD: 'add',
        REMOVE: 'remove',
    },
    GET_ALL_REVIEWS_PRODUCT: 'reviews',
    GET_ALL_REVIEWS_STARS: 'reviewsRating',
    GET_ALL_REVIEWS_PRODUCT_ADMIN: 'adminReviews',
    HIDDEN_REVIEW: 'adminReviews',
    VOUCHER: "Voucher"
};
